esphome:
  name: minimal-waveshare-7
  friendly_name: Minimal Waveshare 7
  min_version: "2025.4.2"


esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  flash_size: 8MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf


# Web server for easy access
web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

captive_portal:

# Wi-Fi and API
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


api:
  encryption:
    key: !secret api_encryption_key


ota:
  - platform: esphome
    password: !secret ota_password
  - platform: web_server

logger:
  baud_rate: 115200
  hardware_uart: UART0
  level: DEBUG
